import lit.formats
import os

config.name = "kagura"
config.test_format = lit.formats.ShTest(True)
config.suffixes = [".ll"]

# Substitutions filled in by lit.site.cfg.py (generated by CMake)
config.substitutions.append(("%opt", config.opt))
config.substitutions.append(("%FileCheck", config.filecheck))
config.substitutions.append(("%kagura_plugin", config.kagura_plugin))
